### ISSUE TITLE
more clear Stack settings

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/ide-haskell-cabal#2]
I'm not sure why this defaulted to 7.8 on my system.

Anyway, I'd want this to use stack.yaml resolver version to determine a project's GHC version ideally.

While everything seems to be working just fine, the settings and name don't make it clear whether this is about Cabal the library versus cabal-install the build tool. It _should_ work for people who use Stack and don't even have cabal-install installed, and that should be clear in the docs. Also, it would be nice to have more clarity about what settings, if any, are relevant for Stack-based projects.

**Comment by wolftune** [comment]
Ah, based on seeing the menu "Cabal > test" this sounds like it is assuming the cabal-install build tool.

Ideally, there could just be a ide-haskell-stack or just a stack setting for this where it uses `stack test` instead of `cabal test` and so on and so forth

**Comment by lierdakil** [comment]
This project focuses on cabal. For stack, we would need separate backend.

**Comment by lierdakil** [comment]
You can literally see it in its name.

**Comment by wolftune** [comment]
yes, but this is not your fault, it's a very confusing name. Stack itself uses Cabal the library, just not cabal-install the tool, so I never feel sure about this.

Anyway, before the separate backend was required, things worked with stack, and yet I got an error without having any backend installed, but then having this makes things work again, which is weird.

I hope you'll add a stack backend ASAP anyway. Thanks

I would suggest if possible that your docs clarify this being about cabal the tool vs Cabal the library,

**Comment by lierdakil** [comment]
That's not an error, strictly speaking, but a warning. And you can disable it in ide-haskell settings, if you don't need/want cabal support.

**Comment by wolftune** [comment]
thanks, that makes sense. Should I open a ticket under ide-haskell for adding a stack backend?

**Comment by lierdakil** [comment]
Well, I have it in the back of my mind anyway, but you can, just in case.
