### ISSUE TITLE
Request:Hotkey support for build/clean...?

### ISSUE THREAD

**Issue by hilaolu** [atom-haskell/ide-haskell-cabal#24]
I am really sorry if this is mentioned elsewhere.I tried  finding the hotkey of these functions.What about adding such a function?
Thankyou.

**Comment by lierdakil** [comment]
Add something like this to [your Atom keymap](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings)
```cson
'atom-workspace':
  'ctrl+b': 'ide-haskell-cabal:build'
  'ctrl+e': 'ide-haskell-cabal:clean'
```

FWIW, this is [briefly mentioned](https://atom-haskell.github.io/core-packages/ide-haskell-cabal/#keybindings) in the Atom-Haskell documentation, too.
