### ISSUE TITLE
ide-haskell-cabal has no notion of multiple projects

### ISSUE THREAD

**Issue by apriori** [atom-haskell/ide-haskell-cabal#3]
Hello, currently I run in an issue if I have multiple opened projects and e.g. want to build a selected one. I'm not aware whether this is a limitation of atom itself, but there seems to be no way to define a current active project. Also not via opening a file in that project. ide-haskell-cabal will try to build whatever is the first project in the open project list.

**Comment by lierdakil** [comment]
Oh. I forgot to fix this before release. I'll see what I can do with this. Thanks for reporting.

**Comment by lierdakil** [comment]
Okay, so I just pushed v0.1.1, which should somewhat alleviate this problem, but it's not a complete solution. With v0.1.1, it starts from currently active editor and tries to find project it belongs to. If that fails, it falls back to first project in project manager. Bear in mind this _will_ somewhat conflict with target selection, i.e. if you have a particular target selected and then try to build another project, it will likely fail. Target selection follows pretty much the same convention (i.e. it will show targets for project associated with currently open editor)

Maybe we could leverage target selection to select a particular project, but I will need to think about it. @edsko, would you happen to have any input on this?

**Comment by edsko** [comment]
Not really. I never have more than one project open. What you implemented sounds reasonable.
