### ISSUE TITLE
Can't spawn cabal

### ISSUE THREAD

**Issue by BillyBadBoy** [atom-haskell/ide-haskell-cabal#7]
I have a trivial HelloWorld project using a cabal sandbox, which I can build OK from the command line, but cannot build from atom because it complains about: `Uncaught Error: spawn cabal ENOENT` .

Cabal is definitely on my path and I can't see anywhere in the package settings to manually configure the cabal location so I can't see how to proceed.

Any idea what the problem could be?

os: linux mint

**Comment by lierdakil** [comment]
What OS are you on?

**Comment by BillyBadBoy** [comment]
Further info:

[1] os: linux mint

[2] selecting: Haskell IDE > Cabal > Set Build target from the menu correctly displays the cabal file targets.

[3] The other Haskell plugins are worling fine (autocomplete, linting etc)

**Comment by lierdakil** [comment]
1) Make sure you don't have `pathExclusive` option enabled in ide-haskell-cabal settings.
2) Check Atom's environment by running `process.env.PATH` in dev. console (View → Developer → Toggle Developer Tools)
3) You can add a directory with `cabal` executable to one of `pathTo7xx` options in ide-haskell-cabal settings. F.ex. if `which cabal` gets you `/usr/local/bin/cabal`, you can write `/usr/local/bin` in `pathTo7xx`. Bear in mind, only one of those is used, depending on `activeGhcVersion` setting.

**Comment by BillyBadBoy** [comment]
[1] `pathExclusive` option is **not** enabled 

[2] `process.env.PATH` produced a much shorter path than when I do `echo $PATH`. This is the root of my problem. I clearly don't understand how paths work !

[3] Adding directory containing cabal to _**Path for GHC 7.10**_ fixed it.

Thanks

**Comment by lierdakil** [comment]
If I had to guess, you probably have `PATH` set up in your `.bashrc` or something similar. `.bashrc` is only run for _interactive_ shells. So when you log in, it doesn't set PATH (due to lack of interactive shells in graphical login). You might be better off to set up environment in e.g. `.bash_profile`, which is run for _login_ shells.

Consult your shell manual for file names, if not using bash.
